---
title: "Pyro Pizza"
output: 
   html_notebook:
      code_folding: hide
      toc: true
      toc_float: true
      theme: simplex
---

<style type="text/css">

body, td {
   font-size: 14px;
}
code.r{
  font-size: 20px;
}
pre {
  font-size: 20px
}
</style>

# Setup

```{r, warning=FALSE, message=FALSE, results='hide'}

library(googlesheets)
library(data.table)
library(dplyr)
library(plyr)
library(lubridate)
library(scales)
library(plotly)
library(ggplot2)
library(weatherData)
library(rwunderground)
library(jsonlite)
knitr::opts_chunk$set(fig.height=5, fig.width=7)
library(zoo)
library(randomForest)
library(timeDate)
library(caret)
library(glmnet)
library(gam)
library(rvest)
library(tidyr)

```

# Helper Functions

```{r}

get_monthly_weather <- function(airport="PDX", date=as.Date("2016-12-19")) {

  url <- paste0('https://www.wunderground.com/history/airport/',airport,'/',
                     year(date),'/',
                     month(date),'/',
                     day(date),'/',
                     'MonthlyHistory.html')

  page <- read_html(url)
  closeAllConnections()
  
  weather_data <- page %>%
    html_nodes("table") %>%
    .[[4]] %>%
    html_table() %>%
    as.data.table()
  
  setnames(weather_data, c("day","temp_max","temp_avg","temp_min",
                           "dew_high","dew_avg","dew_low",
                           "humidity_high","humidity","humidity_low",
                           "pressure_high","pressure_avg","pressure_low",
                           "visibility_high","visibility_avg","visibility_low",
                           "wind_high","wind","wind_dir",
                           "precipitation","conditions"))
  weather_data = weather_data[-1]
  weather_data[,month:=month(date)]
  weather_data[,year:=year(date)]
  weather_data[,date:=ymd(paste(year,month,day,sep="-"))]
  
  # convert columns to numeric
  names = colnames(weather_data)
  ignore = c("conditions","date","precipitation")
  names = names[!names %in% ignore]
  dtnew <- weather_data[,(names):=lapply(.SD, as.numeric), .SDcols = names]
  
  # Sys.sleep(2)
}

get_weather_forecast <- function(airport="PDX")
{
  base_url <- paste0('http://api.wunderground.com/api/',wu.apikey,'/')
  final_url <- paste0(base_url, 'forecast10day/q/',airport, '.json')

  # reading in as raw lines from the web service
  conn <- url(final_url)
  raw_data <- readLines(conn, n=-1L, ok=TRUE)
 # Convert to a JSON
  weather_data <- fromJSON(paste(raw_data, collapse=""))
  close(conn)
  return(weather_data)
}

get_season = function(dates) {
    WS = as.Date("2012-12-15", format = "%Y-%m-%d") # Winter Solstice
    SE = as.Date("2012-3-15",  format = "%Y-%m-%d") # Spring Equinox
    SS = as.Date("2012-6-15",  format = "%Y-%m-%d") # Summer Solstice
    FE = as.Date("2012-9-15",  format = "%Y-%m-%d") # Fall Equinox

    # Convert dates from any year to 2012 dates
    d = as.Date(strftime(dates, format="2012-%m-%d"))

    ifelse (d >= WS | d < SE, "Winter",
      ifelse (d >= SE & d < SS, "Spring",
        ifelse (d >= SS & d < FE, "Summer", "Fall")))
}

get_holiday = function(holidays=listHolidays("US"),dates) {

   years = year(dates)
   years_levels = levels(as.factor(years))
   
   holiday_date = data.table()
   
   for (h in holidays) {
      for (y in years_levels) {
         y = as.list(as.numeric(y))
         holiday_date = rbind(holiday_date,do.call(h,y))
      }
   }
   
   holiday_date = as.Date(holiday_date$`GMT:x`)
   
   holiday = ifelse(dates %in% holiday_date,1,0)
}

get_weather_condition = function(conditions1,conditions2,conditions3) {
   
   if (!is.na(conditions2) & !is.na(conditions3)) {
      c = sample(c(conditions1,conditions2,conditions3),1)
   } else if (!is.na(conditions2)) {
      c = sample(c(conditions1,conditions2),1)
   } else {
      c = conditions1
   }
   return(c)
}

```

# Grabbing the Pyro Inventory Data

```{r}

##############################
# Pyro Pizza Data ############
##############################

# # (my_sheets <- gs_ls())
# # fin2016 = gs_title("2016 Springwater Ledger")
# pyro = gs_key("1MzRbJdaHKv9CJMPeN7Z-WQtdoGuLWAyE9gvYS-_Mgc8")
# # gs_ws_ls(fin2016)
# inventory = pyro %>% gs_read_csv(ws = "12th INVENTORY", skip=0) %>% as.data.table

inventory = setDT(read.csv("inventory.csv"))

# fixing the dates in the 2016 data
setnames(inventory,colnames(inventory),c("date","day","initial_inventory","par","prep_rec","prep_actual","waste","final_inventory","short_long","scale","use_expected","use_actual"))
# ,"temp","precip","clouds","sun","wind","humidity","holiday","event"))
# inventory = inventory[-1]
# inventory[,c("event","temp","precip","clouds","sun","wind","humidity","holiday"):=NULL]
inventory[,date:=mdy(date)]
inventory[,use_actual:=as.double(use_actual)]
# inventory = inventory[use_actual!=0]

```

# Grabbing the Monthly Historical Weather Data

```{r}

date_range <- seq.Date(from=as.Date(min(inventory$date)), to=as.Date(max(inventory$date)), by='1 month')

# Initialize a data frame
weather <- data.table()

# loop over months, and fetch weather data
for(i in seq_along(date_range)) {
    weather_data <- get_monthly_weather("PDX", as.Date(date_range[i]))
    weather <- rbind(weather, weather_data)
    print(i)
}

# getting rid of css scripting
weather[,conditions:=gsub("\n","",conditions)]
weather[,conditions:=gsub("\t","",conditions)]

# filling in blank conditions based on average visibility
weather[conditions=="",conditions:=ifelse(visibility_avg>8,"Overcast","")]
weather[conditions=="",conditions:=
          ifelse(visibility_avg<=8 & visibility_avg>6,"Mostly Cloudy","")]
weather[conditions=="",conditions:=
          ifelse(visibility_avg<=6 & visibility_avg>4,"Partly Cloudy","")]
weather[conditions=="",conditions:=
          ifelse(visibility_avg<=4 & visibility_avg>2,"Scattered Clouds","")]
weather[conditions=="",conditions:=
          ifelse(visibility_avg<=2,"Clear","Unknown")]

# correcting for trace precipitation
weather$precipitation = as.numeric(as.character(weather$precipitation))
weather[is.na(precipitation),precipitation:=0.001]
weather[,snow:=ifelse(grepl("Snow",conditions) & !grepl("Rain",conditions),precipitation,0)]
weather[,rain:=ifelse(grepl("Rain",conditions),precipitation,0)]

# spreading out conditions
weather$conditions = as.character(weather$conditions)
weather[,c("conditions1","conditions2","conditions3") := tstrsplit(conditions, ",", fixed=TRUE)]
# weather[,conditions:=sample(c(conditions1,conditions2,conditions3),1)]
weather[,conditions:=get_weather_condition(conditions1,conditions2,conditions3),by=date]

# save to CSV
# write.csv(weather, file=('weather-09152017.csv'), row.names=FALSE)

# weather = setDT(read.csv(file="PDX-monthly.csv"))

# reducing to the forecast variables
names = colnames(weather)
keep = c("date","temp_max","temp_min","conditions","rain","snow","humidity","wind")
names = names[!names %in% keep]
weather[,(names):=NULL]

table(weather$conditions)
# weather[conditions=="Hail",conditions:="Thunderstorm"]

```

# Grabbing the 10-day Forecast Data

```{r}

wu.apikey = readLines("config.io",warn=F)
rwunderground::set_api_key(wu.apikey)

weather_data <- get_weather_forecast('PDX')
weather_data = setDT(weather.data$forecast$simpleforecast$forecastday)
forecast = data.table(date=seq(Sys.Date(),Sys.Date()+9,by='day'),
                temp_max=weather.data$high[[1]],
                temp_min=weather.data$low[[1]],
                conditions=weather.data$conditions,
                rain=weather.data$qpf_allday[[1]],
                snow=weather.data$snow_allday[[1]],
                humidity=weather.data$avehumidity,
                wind=weather.data$avewind[[1]])

```

# Creating the Features

```{r}

# merging inventory and weather
dt = merge(inventory,weather,by="date")

# adding seasons
dt[,season:=get_season(date)]

# adding holidays
dt[,holiday:=get_holiday(listHolidays("US"),date)]

# adding day of the week
dt[,day:=weekdays(date)]

# adding month
dt[,month:=month(date)]

# creating average use compared to previous 7 days, 3 days, 1 day
dt[,':=' (use7=rollapply(use_actual, width=list(-(7:1)) , FUN=mean, fill="extend"),
          use3=rollapply(use_actual, width=list(-(3:1)) , FUN=mean, fill="extend"),
          use1=rollapply(use_actual, width=list(-(1:1)) , FUN=mean, fill="extend"))]

# eliminating single condition instances
table(dt$conditions)

# partitioning the data
set.seed(111)
inTrain = createDataPartition(dt$conditions, p=0.50)

train = dt[inTrain$Resample1,]
test = dt[-inTrain$Resample1,]

train = copy(dt)

# adding average use for day of week by season
train[!is.na(use_actual),':=' (avgUse=mean(use_actual),
             medUse=median(use_actual),
             quart1Use=quantile(use_actual)[2],
             quart3Use=quantile(use_actual)[4],
             maxUse=max(use_actual)),
      by=.(day,month)]

test[!is.na(use_actual),':=' (avgUse=mean(use_actual),
             medUse=median(use_actual),
             quart1Use=quantile(use_actual)[2],
             quart3Use=quantile(use_actual)[4],
             maxUse=max(use_actual)),
      by=.(day,month)]

# center and scale all numerical features
train[!is.na(use_actual),':=' (temp_maxz=scale(temp_max),
           temp_minz=scale(temp_min),
           humidityz=scale(humidity),
           windz=scale(wind),
           snowz=scale(snow),
           rainz=scale(rain),
           use7z=scale(use7),
           use3z=scale(use3),
           use1z=scale(use1),
           avgUsez=scale(avgUse),
           medUsez=scale(medUse),
           quart1Usez=scale(quart1Use),
           quart3Usez=scale(quart3Use),
           maxUsez=scale(maxUse))]
test[!is.na(use_actual),':=' (temp_maxz=scale(temp_max),
           temp_minz=scale(temp_min),
           humidityz=scale(humidity),
           windz=scale(wind),
           snowz=scale(snow),
           rainz=scale(rain),
           use7z=scale(use7),
           use3z=scale(use3),
           use1z=scale(use1),
           avgUsez=scale(avgUse),
           medUsez=scale(medUse),
           quart1Usez=scale(quart1Use),
           quart3Usez=scale(quart3Use),
           maxUsez=scale(maxUse))]

# making the categorical variables factors
train$day = as.factor(train$day)
train$season = as.factor(train$season)
train$conditions = as.factor(train$conditions)
train$month = as.factor(train$month)
train$holiday = as.factor(train$holiday)
test$day = as.factor(test$day)
test$season = as.factor(test$season)
test$conditions = as.factor(test$conditions)
test$month = as.factor(test$month)
test$holiday = as.factor(test$holiday)

```

# Fitting a Random Forest Model

```{r rforest}

# haven't fixed snowz and removing seasons and conditions

ntrain = train[,.(use_actual,day,conditions,season,holiday,month,
                  temp_maxz,temp_minz,humidityz,windz,rainz,snowz,
                  use7z,use3z,use1z,avgUsez,medUsez,quart1Usez,quart3Usez,maxUsez)]

# preping for fi
ntrain = train[,.(use_actual,day,conditions,season,holiday,month,
                  temp_maxz,temp_minz,humidityz,windz,rainz,snowz,
                  use7z,use3z,use1z,avgUsez,medUsez,quart1Usez,quart3Usez,maxUsez)]
ntest = test[,.(date,use_actual,use_expected,day,conditions,season,holiday,month,
                  temp_maxz,temp_minz,humidityz,windz,rainz,snowz,
                  use7z,use3z,use1z,avgUsez,medUsez,quart1Usez,quart3Usez,maxUsez)]

rfuse = randomForest(use_actual ~ day + holiday + conditions + season + month +
                  temp_maxz + temp_minz + humidityz + windz  + rainz +
                  use7z + use3z + use1z + avgUsez + medUsez + quart1Usez + quart3Usez + maxUsez,
                  data = ntrain[!is.na(use_actual)])

save(rfuse,file="rfuse.RData")

ntest[,use_predicted:=round(predict(rfuse,ntest,type="response"))]
# ntest[,.(date,day,use_actual,use_predicted,use_expected)]

imp = as.data.frame(importance(rfuse))
imp[,2] <- rownames(imp)
imp[order(-imp$IncNodePurity),]

MAE = mean(abs(ntest$use_actual-ntest$use_predicted))
MAE_baseline = mean(abs(ntest$use_actual-ntest$use_expected))

R2 <- 1 - (sum((ntest$use_actual-ntest$use_predicted)^2)/sum((ntest$use_actual-mean(ntest$use_actual))^2))
R2_baseline <- 1 - (sum((ntest$use_actual-ntest$use_expected)^2)/sum((ntest$use_actual-mean(ntest$use_actual))^2))

ggplot(ntest,aes(x=ntest$use_actual)) + 
   geom_point(aes(y=ntest$use_predicted),color="red") +
   geom_point(aes(y=ntest$use_expected),color="blue") +
   geom_abline(slope = 1,intercept = 0)

write.csv(dt,file="pyrodata.csv",row.names=FALSE)

```

# Amount to Prep

```{r}

# creating overflow estimates
dt[,':=' (Date0 = Date - 1,
           Feces0 = .SD[match(Date - 1,.SD[,Date]),Feces],
           Urine0 = .SD[match(Date - 1,.SD[,Date]),Urine],
           Date2 = Date + 1,
           Feces2 = .SD[match(Date + 1,.SD[,Date]),Feces],
           Urine2 = .SD[match(Date + 1,.SD[,Date]),Urine],
           NormFeces2 = .SD[match(Date + 1,.SD[,Date]),NormFeces],
           NormUrine2 = .SD[match(Date + 1,.SD[,Date]),NormUrine],
           Date3 = Date + 2,
           Feces3 = .SD[match(Date + 2,.SD[,Date]),Feces],
           Urine3 = .SD[match(Date + 2,.SD[,Date]),Urine],
           NormFeces3 = .SD[match(Date + 2,.SD[,Date]),NormFeces],
           NormUrine3 = .SD[match(Date + 2,.SD[,Date]),NormUrine]),
    by=Toilet]

```

